name: generate animation

on:
  # Run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"

  # Allow to manually run the job at any time
  workflow_dispatch:

  # Run on every push on the main branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Generates a snake game from a GitHub user's contributions graph and outputs a SVG animation
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3 # Assuming there's a v3, or check the latest version
        with:
          github_user_name: divyashah0510
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Debugging step to verify the directory and files
      - name: Debugging
        run: |
          echo "User: ${{ github.event.repository.owner.login }}"
          ls -l dist

      # Push the content of <build_dir> to a branch
      # The content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as GitHub Page
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
